name: Artist
description: Correct capitalisation for an artist
labels: ['type:artist']
body:
  - type: input
    id: current
    attributes:
      label: Current
      description: How is this artist's name currently capitalised?
      placeholder: "e.g. sAbRina cArpenter"
    validations:
      required: true
  - type: input
    id: correction
    attributes:
      label: Correction
      description: How should this artist's name be capitalised instead?
      placeholder: "e.g. Sabrina Carpenter"
    validations:
      required: true
  - type: input
    id: link
    attributes:
      label: Link
      description: Can you provide the link to the page on Last.fm?
      placeholder: "e.g. https://www.last.fm/music/sAbRina+cArpenter"
    validations:
      required: true
  - type: textarea
    id: sources
    attributes:
      label: Sources
      description: Can you provide reputable sources where this correct capitalisation is present? (RYM and MusicBrainz are invalid, check README)
      placeholder: "e.g. https://open.spotify.com/artist/74KM79TiuVKeVCqs8QtB0B"
    validations:
      required: true
