name: Multiple Albums or Tracks
description: Correct capitalisation for many tracks and albums by one artist, or many tracks on one album
labels: ['type:album_track']
body:
  - type: markdown
      attributes:
        value: "If the following tracks or albums are by different artists, please create separate issues for each artist."
  - type: input
    id: none
    attributes:
  - type: textarea
    id: current
    attributes:
      label: Current
      description: How are these tracks currently capitalised? (List all that need corrections)
      placeholder: "e.g. rUn AwAy WiTh Me\neMotIon\ni RealLY lIkE You"
    validations:
      required: true
  - type: textarea
    id: correction
    attributes:
      label: Correction
      description: How should these tracks be capitalised instead? (In the same order as the above list)
      placeholder: "e.g. Run Away With Me\nEmotion\nI Really Like You"
    validations:
      required: true
  - type: input
    id: link
    attributes:
      label: Link
      description: Can you provide the link to the artist or album on Last.fm?
      placeholder: "e.g. https://www.last.fm/music/Carly+Rae+Jepsen/Emotion"
    validations:
      required: true
  - type: textarea
    id: sources
    attributes:
      label: Sources
      description: Can you provide reputable sources where this correct capitalisation is present? (One source can work for all or some tracks) (RYM and MusicBrainz are invalid, check README)
      placeholder: "e.g. https://open.spotify.com/album/08MsbKas4UJKhbJlAnAyfB"
    validations:
      required: true
