name: Bug report
description: Please don't submit bug reports here
labels: []
body:
  - type: markdown
    attributes:
      value: "This is not the place for reporting bugs, if you are using bleh please head to [this page](https://github.com/katelyynn/bleh/issues/new/choose)"
  - type: input
    id: none
    attributes:
      label: Please read above
    validations:
      required: true
