name: Album or Track
description: Correct capitalisation for an album or track
labels: ['type:album_track']
body:
  - type: input
    id: current
    attributes:
      label: Current
      description: How is this currently capitalised?
    validations:
      required: true
  - type: input
    id: correction
    attributes:
      label: Correction
      description: How should this be capitalised?
    validations:
      required: true
  - type: input
    id: link
    attributes:
      label: Link
      description: Can you provide the link to the page on Last.fm?
    validations:
      required: true
  - type: textarea
    id: sources
    attributes:
      label: Sources
      description: Can you provide reputable sources where this correct capitalisation is present? (RateYourMusic and MusicBrainz are invalid, check README)
    validations:
      required: true
