name: Artist
description: Correct capitalisation for an artist
labels: ['type:artist']
body:
  - type: input
    id: current
    attributes:
      label: Current
      description: How is this currently capitalised?
    validations:
      required: true
  - type: input
    id: correction
    attributes:
      label: Correction
      description: How should this be capitalised?
    validations:
      required: true
  - type: input
    id: link
    attributes:
      label: Link
      description: Can you provide the link to the page on Last.fm?
    validations:
      required: true
  - type: textarea
    id: sources
    attributes:
      label: Sources
      description: Can you provide sources where this capitalisation is present? (RateYourMusic and MusicBrainz are invalid, check README)
    validations:
      required: true
